import { FaCheckCircle } from "react-icons/fa";

export const frontendData = [
            {
              id:1,
              title: "HTML",
              icon: <FaCheckCircle />,
              rating: 4.5,
              level: 'Experienced',
            },
            {
              id:2,
              title: "CSS",
              icon: <FaCheckCircle />,
              rating: 4.5,
              level: 'Experienced',
            },
            {
              id:3,
              title: "Javascript",
              icon: <FaCheckCircle />,
              rating: 4.5,
              level: 'Experienced',
            },
            {
              id:4,
              title: "TypeScript",
              icon: <FaCheckCircle />,
              rating: 3.5,
              level: 'Intermidiate',
            },
            {
              id:5,
              title: "React",
              icon: <FaCheckCircle />,
              rating: 4.0,
              level: 'Experienced',
            },
            {
              id:6,
              title: "React Native",
              icon: <FaCheckCircle />,
              rating: 3.5,
              level: 'Intermidiate',
            },
            {
              id:7,
              title: "Tailwind Css",
              icon: <FaCheckCircle />,
              rating: 4.5,
              level: 'Experienced',
            },
            {
              id:8,
              title: "Bootsrap",
              icon: <FaCheckCircle />,
              rating: 3.5,
              level: 'Intermidiate',
            },
            {
              id:9,
              title: "Jquery",
              icon: <FaCheckCircle />,
              rating: 4.5,
              level: 'Experienced',
            },
            {
              id:10,
              title: "Redux",
              icon: <FaCheckCircle />,
              rating: 4.5,
              level: 'Experienced',
            },
            {
              id:11,
              title: "RTK Query",
              icon: <FaCheckCircle />,
              rating: 4.0,
              level: 'Experienced',
            },
            {
              id:12,
              title: "Axios",
              icon: <FaCheckCircle />,
              rating: 4.5,
              level: 'Experienced',
            },
            {
              id:13,
              title: "Ajax",
              icon: <FaCheckCircle />,
              rating: 4.5,
              level: 'Experienced',
            },
            {
              id:14,
              title: "Search Engine Optimization",
              icon: <FaCheckCircle />,
              rating: 4.0,
              level: 'Experienced',
            },
            {
              id:15,
              title: "Graphql",
              icon: <FaCheckCircle />,
              rating: 3.0,
              level: 'Intermidiate',
            },
            {
              id:16,
              title: "REST API",
              icon: <FaCheckCircle />,
              rating: 4.5,
              level: 'Experienced',
            },
            {
              id:17,
              title: "UI and UX design Principles",
              icon: <FaCheckCircle />,
              rating: 4.5,
              level: 'Experienced',
            },
            {
              id:18,
              title: "CSS Flex and Grid",
              icon: <FaCheckCircle />,
              rating: 4.5,
              level: 'Experienced',
            },
            {
              id:19,
              title: "Responsive Website Design",
              icon: <FaCheckCircle />,
              rating: 4.5,
              level: 'Experienced',
            },
          ]
export const backendData = [
            {
              id:1,
              title: "PHP",
              icon: <FaCheckCircle />,
              rating: 4.5,
              level: 'Experienced',
            },
            {
              id:2,
              title: "Node JS",
              icon: <FaCheckCircle />,
              rating: 4.5,
              level: 'Experienced',
            },
            {
              id:3,
              title: "Python",
              icon: <FaCheckCircle />,
              rating: 3.5,
              level: 'Intermidiate',
            },
            {
              id:4,
              title: "Express JS",
              icon: <FaCheckCircle />,
              rating: 4.5,
              level: 'Experienced',
            },
            {
              id:5,
              title: "PHP Laravel",
              icon: <FaCheckCircle />,
              rating: 4.0,
              level: 'Experienced',
            },
            {
              id:6,
              title: "PHP CodeIgniter",
              icon: <FaCheckCircle />,
              rating: 3.5,
              level: 'Intermidiate',
            },
            {
              id:7,
              title: "Inertia JS",
              icon: <FaCheckCircle />,
              rating: 4.5,
              level: 'Experienced',
            },
            {
              id:8,
              title: "Server Side Rendering(Next Js)",
              icon: <FaCheckCircle />,
              rating: 3.5,
              level: 'Intermidiate',
            },
            {
              id:9,
              title: "MYSQL",
              icon: <FaCheckCircle />,
              rating: 4.5,
              level: 'Experienced',
            },
            {
              id:10,
              title: "SQL",
              icon: <FaCheckCircle />,
              rating: 4.5,
              level: 'Experienced',
            },
            {
              id:11,
              title: "MongoDb",
              icon: <FaCheckCircle />,
              rating: 4.0,
              level: 'Experienced',
            },
            {
              id:12,
              title: "Mongoose",
              icon: <FaCheckCircle />,
              rating: 4.5,
              level: 'Experienced',
            },
            {
              id:13,
              title: "Sequelize",
              icon: <FaCheckCircle />,
              rating: 4.5,
              level: 'Experienced',
            },
            {
              id:14,
              title: "PayMent Gateway Integration",
              icon: <FaCheckCircle />,
              rating: 4.0,
              level: 'Experienced',
            },
            {
              id:15,
              title: "SMS Integration",
              icon: <FaCheckCircle />,
              rating: 3.0,
              level: 'Intermidiate',
            },
            {
              id:16,
              title: "MVC Framework",
              icon: <FaCheckCircle />,
              rating: 4.5,
              level: 'Experienced',
            },
            {
              id:17,
              title: "Cloud Services and Deployment",
              icon: <FaCheckCircle />,
              rating: 4.5,
              level: 'Experienced',
            },
            {
              id:18,
              title: "Git and Github",
              icon: <FaCheckCircle />,
              rating: 4.5,
              level: 'Experienced',
            },
            {
              id:19,
              title: "Application Mailing",
              icon: <FaCheckCircle />,
              rating: 4.5,
              level: 'Experienced',
            },
            {
              id:19,
              title: "Rest API Server",
              icon: <FaCheckCircle />,
              rating: 4.5,
              level: 'Experienced',
            },
            {
              id:19,
              title: "Authentication System and Security Principles",
              icon: <FaCheckCircle />,
              rating: 4.5,
              level: 'Experienced',
            },
          ]

    