export const servicesData = [
            {
              id:1,
              title: 'Graphic Design',
              serviceLists: [
              "Logos and branded elements",
               "Business cards, letterhead & envelopes",
               "Stationary Design",
               "Label Design",
               "Letterhead Design",
               "Signage Design",
               "Billboard Design",
               "Posters and banners",
               "Social media graphics & digital marketing ads",
               "Email marketing graphics",
               "Photo Editing",
               "Picture Enlargement",
               "artistic Picture design",
              ],
            },
            {
              id:2,
              title: 'Web Development And Mobile App Development',
              serviceLists: [
              "Content Management System",
              "IOS and Android app design with react Native",
               "Shopping Cart / Online Ordering System / Online Payments",
               "Event Calendar",
               "Blog / News Management",
               "Social Media Integration — Facebook, Twitter, Youtube, Google+, etc.",
               "Email Newsletter",
               "Mobile-optimized Website",
               "Web Application / Business Software",
               "Web Hosting",
               "Web Site Maintenance",
               "Map Integration",
               "Customer Relationship Management (CRM) Integration",
               "Learning Management System (LMS)",
               "User Interface (UI) Design",
               "User Experience (UX) Design",
               "Search Engine Optimization",
              ],
            },
            {
              id:3,
              title: 'Others',
              serviceLists: [
              "Word Processing",
               "Power Point Presentation",
               "Business Proposal Design",
               "Academic Research Work",
               "Data Analysis",
               "Web Instructor",
               "Digital Marketing",
               "Tech Mentoring",
              ],
            },
          ]